"""Generate src/rx3/fields/rules/_title_words.py: job-title head words from LiveCareer
`jobtitle` tags (a count threshold keeps typos out). Rerun if the CSV changes.

    uv run python tools/build_title_lexicon.py
"""

import csv
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from livecareer_align import CSV_PATH, parse_entries  # noqa: E402

csv.field_size_limit(10**9)
words = Counter()
with open(CSV_PATH, encoding="utf-8", newline="") as f:
    for row in csv.DictReader(f):
        for e in parse_entries(row["Resume_html"]):
            t = e["fields"].get("title", "")
            toks = re.findall(r"[a-z]+", t.lower())
            if toks:
                words[toks[-1]] += 1  # head noun of the title
keep = sorted(w for w, c in words.items() if c >= 4 and len(w) > 2)
body = "\n".join(f'    "{w}",' for w in keep)
(ROOT / "src/rx3/fields/rules/_title_words.py").write_text(
    f'"""GENERATED by tools/build_title_lexicon.py - do not edit."""\n\nTITLE_HEADS = frozenset({{\n{body}\n}})\n', encoding="utf-8")
print(len(keep), "head words")
